services:
  frontend:
    build:
      context: ./frontend/galaxEye # Path to your frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    depends_on:
      - backend # Ensure backend starts before frontend

  backend:
    build:
      context: ./backend # Path to your backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    environment:
      DATABASE_URL: "postgres://postgres:Anush@123@db:5432/FirstDB" # Database connection string
    depends_on:
      - db # Ensure database starts before backend

  db:
    image: postgres:latest # Use the latest PostgreSQL image
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Anush@123
      POSTGRES_DB: FirstDB # Name of the database to create
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data

volumes:
  pgdata: # Define a named volume for PostgreSQL data
